mainback
PotassiumIodideSZ/CouturizeOsnKV pull request #17
Opened 2024-12-14 07:57 UTC by PotassiumIodideSZ

2024-12-14 08:12 UTC, marifleee approved these changes

2024-12-14 08:13 UTC, SpartakDeppershmidtP approved these changes

2024-12-19 11:04 UTC, NBuslaevaS approved these changes

2024-12-26 04:32 UTC, Laggon requested changes
Ветка отстает от основной нужно выполнить слияние изменений

https://github.com/Laggon/docs/blob/main/merge/index.md

2024-12-26 04:37 UTC, Laggon approved these changes

2024-12-26 04:41 UTC, merged