add
PotassiumIodideSZ/CouturizeOsnKV pull request #23
Opened 2024-12-19 10:44 UTC by NBuslaevaS

#3

2024-12-19 10:50 UTC, PotassiumIodideSZ approved these changes

2024-12-19 11:00 UTC, marifleee approved these changes

2024-12-19 11:18 UTC, SpartakDeppershmidtP approved these changes

2024-12-26 07:45 UTC, Laggon requested changes
Белый экран при запуске и в консоли разработчика браузера ошибка, что не найден файл `/src/css/app.scss`

2024-12-26 10:22 UTC, marifleee approved these changes

2024-12-26 11:15 UTC, Laggon approved these changes

2024-12-26 11:30 UTC, merged