Обновление ридми
PotassiumIodideSZ/CouturizeOsnKV pull request #5
Opened 2024-12-05 12:08 UTC by SpartakDeppershmidtP

#1

2024-12-13 11:57 UTC, NBuslaevaS approved these changes

2024-12-13 11:59 UTC, PotassiumIodideSZ approved these changes

2024-12-14 08:10 UTC, marifleee approved these changes

2024-12-19 11:47 UTC, Laggon requested changes
Еще стоит описать или перенести часть в файл Техническое задание

2024-12-19 11:47 UTC, Laggon commented on README.md
> +- [Бэкенд (Django)](./CouturizeBackDjango/README.md)
Установку и запуск стоит описывать вместе с добавлением минимального проекта

2024-12-19 11:47 UTC, Laggon commented on README.md
> +- [Бэкенд (Django)](./CouturizeBackDjango/README.md)
И указать ссылку на него в README

2024-12-21 14:14 UTC, PotassiumIodideSZ approved these changes

2024-12-23 06:56 UTC, Laggon requested changes
> Установку и запуск стоит описывать вместе с добавлением минимального проекта

Добавление минимального проекта и соответственно инструкция по запуску к нему это отдельный PR, поэтому в данном PR необходимо добавить общую информацию о проекте в README.md и более подробно в Техническом задании

2024-12-25 13:34 UTC, Laggon approved these changes

2024-12-25 16:07 UTC, merged